apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - namespace.yaml
  # Prometheus
  - prometheus/clusterrole.yaml
  - prometheus/prometheus-config.yaml
  - prometheus/alerting-rules.yaml
  - prometheus/deployment.yaml
  - prometheus/service.yaml
  # AlertManager
  - alertmanager/config.yaml
  - alertmanager/deployment.yaml
  - alertmanager/service.yaml
  # Grafana
  - grafana/configmap.yaml
  - grafana/deployment.yaml
  - grafana/service.yaml
  # Loki + Promtail
  - loki/configmap.yaml
  - loki/deployment.yaml
  - loki/service.yaml
  - promtail/configmap.yaml
  - promtail/daemonset.yaml
  - promtail/rbac.yaml
  # OpenTelemetry
  - otel-collector.yaml
  # Incident Management
  - incident-receiver/deployment.yaml

  # Self-Healing
  - selfhealing/deployment.yaml
  - selfhealing/service.yaml

labels:
  - pairs:
      project: SolidaryTech
      managed-by: argocd
    includeSelectors: false
