apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: solidarytech-root
  namespace: argocd
  labels:
    team: solidarytech
    component: app-of-apps
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: solidarytech
  source:
    repoURL: git@github.com:rgstn/hackathon-solidarytech.git
    targetRevision: main
    path: kubernetes/argocd
    directory:
      recurse: false
      exclude: '{install.yaml,app-of-apps.yaml}'
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 5m
