apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: solidarytech
  namespace: argocd
spec:
  description: "SolidaryTech Microservices Platform"
  sourceRepos:
    - "git@github.com:rgstn/hackathon-solidarytech.git"
  destinations:
    - namespace: solidarytech
      server: https://kubernetes.default.svc
    - namespace: monitoring
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: argoproj.io
      kind: Application
    - group: argoproj.io
      kind: AppProject
  namespaceResourceWhitelist:
    - group: ""
      kind: "*"
    - group: apps
      kind: "*"
    - group: autoscaling
      kind: "*"
    - group: networking.k8s.io
      kind: "*"
    - group: policy
      kind: "*"
    - group: argoproj.io
      kind: "*"
