apiVersion: apps/v1
kind: Deployment
metadata:
  name: volunteer-service
  namespace: solidarytech
  labels:
    app: volunteer-service
    version: v1
    team: solidarytech
    cost-center: ngo-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: volunteer-service
  template:
    metadata:
      labels:
        app: volunteer-service
        version: v1
        team: solidarytech
        cost-center: ngo-core
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8082"
        prometheus.io/path: "/metrics"
    spec:
      automountServiceAccountToken: false
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - volunteer-service
                topologyKey: kubernetes.io/hostname
      containers:
        - name: volunteer-service
          image: solidarytech/volunteer-service:bootstrap
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 192Mi
            limits:
              cpu: 250m
              memory: 384Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /ready
              port: 8082
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 5
          envFrom:
            - configMapRef:
                name: volunteer-service-config
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: solidarytech-secrets
                  key: DATABASE_URL
