apiVersion: v1
kind: Service
metadata:
  name: volunteer-service
  namespace: solidarytech
  labels:
    app: volunteer-service
    team: solidarytech
    cost-center: ngo-core
spec:
  type: ClusterIP
  selector:
    app: volunteer-service
  ports:
    - name: http
      port: 8082
      targetPort: 8082
      protocol: TCP
