apiVersion: v1
kind: ConfigMap
metadata:
  name: donation-service-config
  namespace: solidarytech
  labels:
    app: donation-service
    team: solidarytech
    cost-center: ngo-core
data:
  SERVICE_NAME: "donation-service"
  SERVICE_PORT: "8081"
  LOG_LEVEL: "INFO"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.monitoring:4317"
  OTEL_SERVICE_NAME: "donation-service"
  ENVIRONMENT: "production"
  WORKER_METRICS_PORT: "8091"
  DYNAMODB_TABLE_NAME: "solidarytech-transactions"
  AWS_REGION: "us-east-1"
  REDIS_URL: "redis://solidarytech-redis.ur9imp.0001.use1.cache.amazonaws.com:6379/0"
