apiVersion: v1
kind: Service
metadata:
  name: donation-service
  namespace: solidarytech
  labels:
    app: donation-service
    team: solidarytech
    cost-center: ngo-core
spec:
  type: ClusterIP
  selector:
    app: donation-service
    component: api
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      protocol: TCP
