apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngo-service
  namespace: solidarytech
spec:
  template:
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
      containers:
        - name: ngo-service
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: gunicorn
              mountPath: /app/.gunicorn
      volumes:
        - name: tmp
          emptyDir: {}
        - name: gunicorn
          emptyDir: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: donation-service
  namespace: solidarytech
spec:
  template:
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
      containers:
        - name: donation-service
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: gunicorn
              mountPath: /app/.gunicorn
      volumes:
        - name: tmp
          emptyDir: {}
        - name: gunicorn
          emptyDir: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: donation-worker
  namespace: solidarytech
spec:
  template:
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
      containers:
        - name: donation-worker
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: volunteer-service
  namespace: solidarytech
spec:
  template:
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
      containers:
        - name: volunteer-service
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: gunicorn
              mountPath: /app/.gunicorn
      volumes:
        - name: tmp
          emptyDir: {}
        - name: gunicorn
          emptyDir: {}
