apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngo-service
  namespace: solidarytech
  labels:
    app: ngo-service
    version: v1
    team: solidarytech
    cost-center: ngo-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ngo-service
  template:
    metadata:
      labels:
        app: ngo-service
        version: v1
        team: solidarytech
        cost-center: ngo-core
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      automountServiceAccountToken: false
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - ngo-service
                topologyKey: kubernetes.io/hostname
      containers:
        - name: ngo-service
          image: 945179326264.dkr.ecr.us-east-1.amazonaws.com/solidarytech/ngo-service:sha-16c57a88-1-1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 192Mi
            limits:
              cpu: 250m
              memory: 384Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 5
          envFrom:
            - configMapRef:
                name: ngo-service-config
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: solidarytech-secrets
                  key: DATABASE_URL
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: solidarytech-secrets
                  key: REDIS_URL
