apiVersion: v1
kind: Service
metadata:
  name: ngo-service
  namespace: solidarytech
  labels:
    app: ngo-service
    team: solidarytech
    cost-center: ngo-core
spec:
  type: ClusterIP
  selector:
    app: ngo-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
